SENSOR_RANGE=80
SERVER_COMM_RANGE = 160
ROBOT_COMM_RANGE = 80
DISTANCE_WEIGHT = 1
OUT_RANGE_STEP = 20


MAX_EPS_STEPS=196
K_SIZE = 30

NUM_DENSE_COORDS_WIDTH=50
CUR_AGENT_KNN_RAD=80
GLOBAL_GRAPH_KNN_RAD=160

UTILITY_CALC_RANGE=40

GLOBAL_NODES_TO_FRONTIER_AVOID_SPARSE_RAD=120